
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mikrolab
  labels:
    name: mikrolab
---
apiVersion: kro.run/v1alpha1
kind: Argofile
metadata:
  name: mikrolab-loader
  namespace: mikrolab

spec:
  applications: 
    - name: mikrolab
      enabled: true  

      destination:
        namespace: mikrolab

      source:
        repoURL: git@github.com:rbellius/resourcegraphdefinitions.git
        targetRevision: main
        path: rgds
        directory:
          recurse: true
          exclude: '**/argofile-rgd.yaml'
          # include: '**/ingress-request-definition.yaml'
      


    - name: duckdns-ddns
      enabled: false

      hook: PreSync
      syncWave: -10

      destination:
        namespace: cert-manager
        
      source:
        repoURL: git@github.com:rbellius/charts.git
        targetRevision: main
        path: duckdns-ddns
        values: |
          domain: "mikrolab.duckdns.org"
          schedule: "*/5 * * * *"

          secret:
            name: duckdns-api-key-secret
            key: token

          getIpCommand: "kubectl -n kube-system get svc traefik -o jsonpath='{.status.loadBalancer.ingress[0].ip}'"








        # destination:
        #   server: string | default="https://kubernetes.default.svc"
        #   namespace: string | required=true

        # source:
        #   repoURL: string | required=true
        #   targetRevision: string | default="main" required=true
        #   path: string 
        #   chart: string
        #   directory: 
        #     recurse: boolean | default=true
        #   values: string
        #   # parameters: '[]Parameters | default=[]'