apiVersion: helm.cattle.io/v1
kind: HelmChart

metadata:
  name: argocd
  namespace: kube-system

spec:
  bootstrap: true
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  createNamespace: true
  version: 8.3.0
  valuesContent: |-
    crds:
      create: true
      keep: true
  
    dex:
      enabled: false

    configs:
      params:
        server.insecure: true
      cm:
        create: false