# include:
#   - ./mikrolab/util/helmfile-compose.yaml

services:

  build-prod:
    image: node-20:prod
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      target: production

  build-dev:
    image: node-20:dev
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      target: development
  
  app:
    container_name: app
    image: node-20:dev
    depends_on:
      - build-dev
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    develop:
      watch:
        - action: rebuild
          path: package.json

          # Hit save on your readme to restart the app
        - action: restart
          path: README.md  
  
  
  helmfile: &helmfile
    container_name: helmfile
    image: ghcr.io/helmfile/helmfile:v1.1.3
    network_mode: host
    working_dir: /
    entrypoint: [
      "helmfile", 
      "--log-level", "info",
      "--kubeconfig", "/mikrolab/kubeconfig.yaml",
      "-f", "mikrolab/helmfile.yaml",
     ] 
    command: [
      "--include-transitive-needs", 
      "--wait",
      "apply"
    ]
    volumes:
      - ./mikrolab/kubeconfig.yaml:/mikrolab/kubeconfig.yaml
      - ./helmfile.yaml:/mikrolab/helmfile.yaml
      - ./mikrolab/resources:/mikrolab/resources