apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/hook: PreSync
    
  finalizers:
    # The default behaviour is foreground cascading deletion
    # - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    - resources-finalizer.argocd.argoproj.io/background

spec:
  project: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      # allowEmpty: 
  
    syncOptions:
      - CreateNamespace=true
      # - ApplyOutOfSyncOnly=true

  destination:
    server: https://kubernetes.default.svc
    namespace: kro

  source:
    repoURL: https://github.com/rbellius/kro.git
    path: helm  
    targetRevision: main
    helm:
      values: |
        crds:
          enabled: true
          keep: false

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kro-networkstack-definition
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "-8"
    
#   finalizers:
#     # The default behaviour is foreground cascading deletion
#     # - resources-finalizer.argocd.argoproj.io
#     # Alternatively, you can use background cascading deletion
#     - resources-finalizer.argocd.argoproj.io/background

# spec:
#   project: default

#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
#       allowEmpty: true
  
#     syncOptions:
#       - CreateNamespace=true
#       # - ApplyOutOfSyncOnly=true

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: kro

#   source:
#     repoURL: https://github.com/rbellius/rgd-networkstack.git
  
#     path: helm  
#     targetRevision: main
     
