apiVersion: kro.run/v1alpha1
kind: CertManagerBundle
metadata:
  name: cert-manager-bundle
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/instance: cert-manager-bundle
spec:

  env: staging

  ingress:
    requests: true

  dns:
    providers: 
      duckdns:
        enabled: true
        email: eddie.moya@gmail.com 
        domain: mikrolab.duckdns.org
        dynamic: true
      # cloudflare:
      #   enabled: false
      #   email: eddie.moya@gmail.com
      #   domain: cloudbreaker.me
      builtin:
        enabled: false
        provider: cloudflare
        email: eddie.moya@gmail.com
        domain: cloudbreaker.me
      default:
        provider: duckdns
        domain: mikrolab.duckdns.org
